// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS0n8cxgfpo9lsA4oEGQa5ZyfY6PrQfB8',
    appId: '1:583539557800:web:5f56b1ca25eed9973d899d',
    messagingSenderId: '583539557800',
    projectId: 'my-english-pal-web',
    authDomain: 'my-english-pal-web.firebaseapp.com',
    storageBucket: 'my-english-pal-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEqfr6CjLMIuQ8mug55kIA7rTAyCk_9yQ',
    appId: '1:583539557800:android:e4ee279d1c4c51913d899d',
    messagingSenderId: '583539557800',
    projectId: 'my-english-pal-web',
    storageBucket: 'my-english-pal-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6o9NrBY-GgE1tpBGQzb9is9oSK_vS_o8',
    appId: '1:583539557800:ios:e55f7a843b47363c3d899d',
    messagingSenderId: '583539557800',
    projectId: 'my-english-pal-web',
    storageBucket: 'my-english-pal-web.appspot.com',
    iosClientId: '583539557800-tfcvd9gmtpuhbfb52nkfs0bkl22cq0t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myenglishpalWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6o9NrBY-GgE1tpBGQzb9is9oSK_vS_o8',
    appId: '1:583539557800:ios:e55f7a843b47363c3d899d',
    messagingSenderId: '583539557800',
    projectId: 'my-english-pal-web',
    storageBucket: 'my-english-pal-web.appspot.com',
    iosClientId: '583539557800-tfcvd9gmtpuhbfb52nkfs0bkl22cq0t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myenglishpalWeb',
  );
}
