// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQKhmLY6kddE2RqfLRz9BeI3Vc1YaT9w',
    appId: '1:374517583382:web:5c269403133da966256f37',
    messagingSenderId: '374517583382',
    projectId: 'my-english-pal-6e6e7',
    authDomain: 'my-english-pal-6e6e7.firebaseapp.com',
    storageBucket: 'my-english-pal-6e6e7.appspot.com',
    measurementId: 'G-VPND06TBMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5anXLYSQwTUG5X8_UT-fP5dVGFHypp4M',
    appId: '1:374517583382:android:e6e9f15357ba2488256f37',
    messagingSenderId: '374517583382',
    projectId: 'my-english-pal-6e6e7',
    storageBucket: 'my-english-pal-6e6e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkgWbyXmpEcbs0mZ1jNeVrCUHGHwEIhQ8',
    appId: '1:374517583382:ios:56cad65ff4835b69256f37',
    messagingSenderId: '374517583382',
    projectId: 'my-english-pal-6e6e7',
    storageBucket: 'my-english-pal-6e6e7.appspot.com',
    iosClientId: '374517583382-pebrjooujqmr5judlhvhnisimfnn9t2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myenglishpalWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkgWbyXmpEcbs0mZ1jNeVrCUHGHwEIhQ8',
    appId: '1:374517583382:ios:56cad65ff4835b69256f37',
    messagingSenderId: '374517583382',
    projectId: 'my-english-pal-6e6e7',
    storageBucket: 'my-english-pal-6e6e7.appspot.com',
    iosClientId: '374517583382-pebrjooujqmr5judlhvhnisimfnn9t2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myenglishpalWeb',
  );
}
